### ISSUE TITLE
Logo and site title should all link to one place in the header component

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1009]
The logo, site title, regional identifier, all of it should link to the site's homepage. 

<img width="1571" alt="Screen Shot 2022-07-26 at 1 58 21 PM" src="https://user-images.githubusercontent.com/2205158/181078133-ea5cc556-e11b-4b5a-83d1-28211a32bd12.png">

**Comment by Jura** [comment]
Verified https://develop.design-system.pages.dev/?path=/story/components-navigation-components-main-navigation-country-header--country-header

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in Dev

**Comment by mrelevo** [comment]
verified in storybook, already implemented in Drupal
