### ISSUE TITLE
What is URL for table.min.css

### ISSUE THREAD

**Issue by JinIgarashi** [undp/design-system#1136]
According to the following storybook, your table component has table.min.css, however, https://undp.github.io/design-system/css/components/table.min.css URL does not exist.

https://design.undp.org/?path=/docs/foundation-typography-table--table

Furthermore, I could not find any source code for table component.

**Comment by theadamparker** [comment]
@JinIgarashi thank you for pointing this out. It is a mistake in the documentation. All table styles are made available in the [base-minimal.min.css](https://undp.github.io/design-system/css/base-minimal.min.css) file. After loading the base-minimal file you will have access to all table styles.
