### ISSUE TITLE
Article template is missing yellow background for callout 

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1157]
With the implementation of the global accent color selector in Storybook, the Article template is no longer displaying a yellow background when the "default" global accent color is selected. The callout does respect the selection of yellow, red, etc. but when "default" is selected it shows no background, rather than the yellow background. 

<img width="1482" alt="Screenshot 2023-03-08 at 2 28 48 PM" src="https://user-images.githubusercontent.com/2205158/223824521-3eaf4f2a-4676-4f50-87f4-54b914a94c8b.png">

**Comment by Jura** [comment]
@mrelevo , ready for verification (when build is over)

**Comment by mrelevo** [comment]
verified in DEv

![image](https://user-images.githubusercontent.com/10246056/224336318-ec55cfec-c8c9-4af7-ab8c-921289e5f1bd.png)

**Comment by mrelevo** [comment]
verified in storybook
