### ISSUE TITLE
Update headers styling for languages which are not using Sohne font

### ISSUE THREAD

**Issue by Jura** [undp/design-system#1212]
For languages which are not supported by Sohne (for example cyrillic family) design system falls back to ProximaNova or another font (UNBangla for Bengali, Google Noto Sans for Burmese, etc) but font presentation differs significantly since Sohne is bold by default. 
Need to update stylings for Sohne replacements using `font-weight: 700` as a default baseline.

**Comment by mrelevo** [comment]
verified in Dev
