### ISSUE TITLE
Menu items should use consistent and accessible states

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1247]
Currently the menu items for 1) sidebar, 2) dropdown menu, and 3) language switcher use inconsistent treatments for hover effects. Furthermore, not all treatments are consistently visible ([example](https://www.dropbox.com/scl/fi/zqv9qpqsp8p76xuc8gvo4/IMG_1404.mov?rlkey=1v092dybzdulv3947wnrglu4o&dl=0)).

<img width="1262" alt="Screen Shot 2023-07-07 at 10 38 35 AM" src="https://github.com/undp/design-system/assets/2205158/0b263a78-39b2-4796-8325-60a073db4705">

The state for these components should be reviewed and aligned.

**Comment by vern-gora** [comment]
I have tried various style configurations and also changed the color to shades very close to `#edeff0`, but the gray hover effect still doesn't display on the second monitor (although it works fine with other colors). I think the issue might be with the second monitor or possibly the use of GPU resources.
When the browser uses GPU, it increases performance, but sometimes there are issues with rendering graphics, especially on the second monitor. Problems such as anomalies in page rendering, decreased performance, or incorrect rendering of certain graphical effects (e.g., animations or hovers) can occur.
