### ISSUE TITLE
"Regional identifier" is black instead of gray

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1309]
The [small regional identifier text (shown here as "region")](https://design.undp.org/?path=/story/components-navigation-components-main-navigation-country-header--country-header) is currently black. It should be gray, matching the color from the Figma file.

Currently:
![Screen Shot 2023-11-07 at 10 10 38 AM](https://github.com/undp/design-system/assets/2205158/84328982-ffe6-47ed-9026-86e504a53105)

Should be `$gray-600`
<img width="713" alt="Screen Shot 2023-11-07 at 10 07 24 AM" src="https://github.com/undp/design-system/assets/2205158/612d917f-4fd2-40f9-9864-0e30207efab0">

**Comment by Jura** [comment]
@theadamparker over to you for validation and PR review: #1310
