### ISSUE TITLE
Page hero should allow an object position option

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1323]
The [page hero component](https://design.undp.org/?path=/docs/components-ui-components-hero-page-pagehero--docs)'s image currently covers the space and is positioned in the center. However this can be a limitation for images which should be positioned differently for mobile

## Example

This photo has a subject to the right side of the frame. It works well for desktop presentations. However, when viewing on a mobile-sized screen the subject is cut off due to the object position being set to center. 

<img width="1059" alt="Screenshot 2024-06-07 at 8 03 38 PM" src="https://github.com/undp/design-system/assets/2205158/fdbfe2f6-afe7-4487-b37e-b9b9d332e3f1">

## Proposed solution

The component should allow an option for mobile image position: left, center, right. This option could add a class to modify the image's object position.

**Comment by Jura** [comment]
@CalebLuster , I can't see the control in the UI: https://issue-1323-object-position-o.design-system.pages.dev/?path=/story/components-ui-components-hero-page-pagehero--page-hero-full-width

**Comment by Jura** [comment]
@theadamparker , check out implementation by @CalebLuster here: https://issue-1323-object-position-o.design-system.pages.dev/?path=/story/components-ui-components-hero-page-pagehero--page-hero-full-width , we will merge #1326 if you are ok with it

**Comment by theadamparker** [comment]
@theadamparker @CalebLuster looks good to me 👍
