### ISSUE TITLE
Language switcher uses incorrect hover colors for its white variant.

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1335]
[The language switcher in white](https://design.undp.org/?path=/story/components-ui-components-language-switcher--language-switcher&args=variant:white) should not have a blue hover for icon and chevron. This appearance is visible for both the hover and focus states. 

We need to find a way for Chromatic to catch such regressions

https://github.com/user-attachments/assets/393b0820-adb1-48c5-ab75-feb3f17db246

**Comment by vern-gora** [comment]
@theadamparker everything looks good now, check it out please

**Comment by theadamparker** [comment]
Looks good to me. Thanks @vern-gora
