### ISSUE TITLE
[SB8]: some components controls inadvertently exposing internal properties

### ISSUE THREAD

**Issue by Jura** [undp/design-system#1358]
Multiple components affected, example: https://develop.design-system.pages.dev/?path=/story/foundation-logos--pnud-logo-blue 
![image](https://github.com/user-attachments/assets/06c2374f-840b-49c7-8eac-33508e2b5053)

**Comment by theadamparker** [comment]
Link component is exposing a "variant" control which isn't needed.

https://develop.design-system.pages.dev/?path=/story/foundation-typography-links--link-story

![Screenshot 2024-09-12 at 5 26 43 PM](https://github.com/user-attachments/assets/bc672c2e-4516-444d-86ee-e4ad50e57409)

**Comment by theadamparker** [comment]
"Checkbox" component is exposing `label_pos`

https://develop.design-system.pages.dev/?path=/story/components-forms-checkbox--checkbox-story

![Screenshot 2024-09-12 at 5 28 38 PM](https://github.com/user-attachments/assets/109b3d3f-cc1b-4638-871b-56a97bbb773f)

**Comment by theadamparker** [comment]
[Accordion](https://develop.design-system.pages.dev/?path=/story/components-ui-components-accordion--accordion-story&globals=locale:english;accent:red;backgrounds.grid:!false;backgrounds.value:transparent) is exposing `headerText` and `descriptionText`

![Screenshot 2024-09-13 at 11 07 11 AM](https://github.com/user-attachments/assets/f5d486da-e913-4439-a42e-d5428212f131)

**Comment by theadamparker** [comment]
[Author card](https://develop.design-system.pages.dev/?path=/story/components-ui-components-authors-author-card--authorcard-story&args=button_option:Inline&globals=locale:english;backgrounds.grid:!false;backgrounds.value:transparent) is exposing `type` and `button_option`.

![Screenshot 2024-09-13 at 11 09 53 AM](https://github.com/user-attachments/assets/cf357686-eddc-4690-a053-6151b7914a94)

**Comment by theadamparker** [comment]
[Parallax cards](https://develop.design-system.pages.dev/?path=/story/components-ui-components-cards-parallax-cards--parallax-cards-story&globals=locale:english;backgrounds.grid:!false;backgrounds.value:transparent) is exposing `locale`.

![Screenshot 2024-09-13 at 11 31 33 AM](https://github.com/user-attachments/assets/1c4b1542-5f4b-4c06-bdbc-edc43579a19f)

**Comment by CalebLuster** [comment]
fixed

**Comment by Jura** [comment]
Verified
