### ISSUE TITLE
[SB8]: Nested component's controls exposed but not functional

### ISSUE THREAD

**Issue by Jura** [undp/design-system#1361]
Author card component has no changeable elements, only one specific button style is used there
https://develop.design-system.pages.dev/?path=/story/components-ui-components-authors-author-card--authorcard-story

Options appearing in Control tab are from the Button element and should not be exposed there:
![image](https://github.com/user-attachments/assets/60f49a39-8ce5-449e-9558-9b9cb8316c5b)

Same here: https://develop.design-system.pages.dev/?path=/story/patterns-filter-and-search-sidebar--filter-and-search-bar-story&args=Height:Fix+height, possible other occurrences, requires further testing

**Comment by CalebLuster** [comment]
I believe this is fixed now

**Comment by Jura** [comment]
You are right, closing
