### ISSUE TITLE
[SB8] H1 styling in docs is using Proxima Nova instead of Söhne Breit

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1365]
H1 tags use the wrong typeface.

![Screenshot 2024-09-12 at 5 30 44 PM](https://github.com/user-attachments/assets/34837d36-aab2-4e59-8d7f-ca5dd29ad453)

**Comment by CalebLuster** [comment]
I don't seem to be getting this bug

![image](https://github.com/user-attachments/assets/bbc28768-f4f4-45b2-a227-9b55a6c0e5dd)

The image on the left is local and the right is the current design system. I have check multiple different docs and they all appear correct.

@Jura and @theadamparker can you pull the recent changes and please check this on your machine to see if its behaving as its supposed to? Maybe a previous ticket fix also fixed this?

**Comment by theadamparker** [comment]
I'm also not seeing it anymore @CalebLuster. @Jura did you push any fixes for this?

**Comment by Jura** [comment]
Nope, closing as it is not replicable
