### ISSUE TITLE
"Breadcrumbs" component has the page title styled incorrectly in the docs

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1366]
For the[ Breadcrumb docs only](https://design.undp.org/?path=/docs/components-navigation-components-breadcrumbs--docs), the page title and the `/` characters are using the wrong font size.
![Screenshot 2024-09-13 at 10 43 04 AM](https://github.com/user-attachments/assets/ec9c5a75-1284-4a49-b97e-a33e2873d0e2)

The font size for page title in the actual component is correct—this error is only for the display within the docs page.

**Comment by Jura** [comment]
Not an issue anymore: https://post-sb8-upgrade-fixes.design-system.pages.dev/?path=/story/components-navigation-components-breadcrumbs--breadcrumbs, closing
