### ISSUE TITLE
[SB8] "Main navigation" docs aren't formatting HTML properly

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1368]
For the docs components within the "Main navigation" category there are large chunks of HTML which are not showing line breaks. The [Country header - Dropdown menu](https://develop.design-system.pages.dev/?path=/docs/components-navigation-components-main-navigation-country-header-dropdown-menu--docs&args=Color:White&globals=locale:english;accent:red;backgrounds.grid:!false;backgrounds.value:transparent), and [Country Site Header](https://develop.design-system.pages.dev/?path=/docs/components-navigation-components-main-navigation-country-site-header--docs&args=Color:White&globals=locale:english;accent:red;backgrounds.grid:!false;backgrounds.value:transparent) docs both have issues, but slightly different.

They both place all the HTML on a single line.

![Screenshot 2024-09-13 at 10 47 58 AM](https://github.com/user-attachments/assets/01c0598c-0626-46aa-80fb-892813057bd5)

The correct appearance is visible in SB7, with HTML line breaks allowing the text to be legible.
![Screenshot 2024-09-13 at 10 51 20 AM](https://github.com/user-attachments/assets/249fa236-42bc-40ba-8622-5b89108ca350)

**Comment by CalebLuster** [comment]
fixed

**Comment by Jura** [comment]
Verified
