### ISSUE TITLE
[SB8] "Country header" controls panel is not showing any controls

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1369]
For the Country header component there should be controls for `enable CTA` and `extended menu`. These are there in SB7 but not SB8.

![Screenshot 2024-09-13 at 10 54 13 AM](https://github.com/user-attachments/assets/b14bc57b-ae91-40de-9c17-738ef4397521)

**Comment by CalebLuster** [comment]
fixed

**Comment by Jura** [comment]
Verified
