### ISSUE TITLE
Featured content card has docs typos

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1372]
- [ ] The [featured card docs](https://design.undp.org/?path=/docs/components-ui-components-cards-featured-card--docs) has the wrong title. It should be **featured** (with a "d" at the end).
- [ ] CSS references aren't proper hyperlinks to the CDN (`cta-link.min.css` and `featured-content-card.min.css`)

![Screenshot 2024-09-13 at 11 28 02 AM](https://github.com/user-attachments/assets/38b929cc-6755-4bfa-ab6f-9214e891f945)

![Screenshot 2024-09-13 at 11 28 35 AM](https://github.com/user-attachments/assets/a42e7840-172a-4d1a-8e1e-65f034a222bc)

**Comment by theadamparker** [comment]
[Image reveal card docs](https://design.undp.org/?path=/docs/components-ui-components-cards-featured-card--docs) has the same CSS link issue

**Comment by Jura** [comment]
Fixed

**Comment by Jura** [comment]
Fixed
