### ISSUE TITLE
[SB8] Image reveal cards docs is exposing React code

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1373]
See image of the [image reveal cards docs](https://develop.design-system.pages.dev/?path=/docs/patterns-card-grids-image-reveal-cards--docs&globals=locale:english;backgrounds.grid:!false;backgrounds.value:transparent) here:
![Screenshot 2024-09-13 at 11 47 29 AM](https://github.com/user-attachments/assets/18196a34-b3e2-4153-8976-1fb2983a6856)

**Comment by CalebLuster** [comment]
fixed

**Comment by Jura** [comment]
Verified
