### ISSUE TITLE
[SB8] Filter and search sidebar docs has stripped out some HTML code

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1374]
The [documentation for custom events](https://develop.design-system.pages.dev/?path=/docs/patterns-card-grids-image-reveal-cards--docs&globals=locale:english;backgrounds.grid:!false;backgrounds.value:transparent) is different in SB8.

![Screenshot 2024-09-13 at 11 49 24 AM](https://github.com/user-attachments/assets/9c0aeec7-822a-4a12-8669-7dc6474f859a)

**Comment by CalebLuster** [comment]
Fixed with html entities

**Comment by Jura** [comment]
Confirmed
