### ISSUE TITLE
Accordion behaviors are not working properly

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1384]
For the [Accordion component](https://design.undp.org/?path=/docs/components-ui-components-accordion--docs) the `multi-expand` and `active` states noted in the documentation are not actually working. See this [Codepen demonstrating the issue.](https://codepen.io/theadamparker/pen/qBeEJjZ?editors=1010)

**Comment by Jura** [comment]
Fixed, assets will be available through NPM within half an hour (version 1.3.1)
