### ISSUE TITLE
Footer "simple" variant is text item misaligned

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1395]
The footer component in its simple variant has terms of use, bottom right, which is misaligned at very wide screens. It should be right-aligned.

Current state:
![Screenshot 2024-10-07 at 4 28 54 PM](https://github.com/user-attachments/assets/c24c1b92-f591-46e3-a48e-cf8216e24f79)

**Comment by CalebLuster** [comment]
@theadamparker made a new branch and pushed to it for a fix.

**Comment by theadamparker** [comment]
Looks good @CalebLuster
