### ISSUE TITLE
Homepage hero: split should have the CTA moved

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1396]
For the [homepage hero split component](https://design.undp.org/?path=/story/components-ui-components-hero-homepage--home-page-hero-split-story&globals=viewport:small), the CTA should be redesigned to be beneath the title, rather than under the image. With this current position under the image it can be unclear that the CTA is for this element, especially when placed alongside competing content. 

![Screenshot 2024-10-07 at 4 55 22 PM](https://github.com/user-attachments/assets/e8f8609d-b0ed-49e7-bea0-b6f06bb475af)

<img width="552" alt="image (1)" src="https://github.com/user-attachments/assets/6d4c8166-8de8-450c-9707-aab6c6f8deac">

It should first be redesigned in Figma.

**Comment by theadamparker** [comment]
Design is available on the Figma branch here:
https://www.figma.com/design/WJSRV3CbcHuVWRQApwvWIm/branch/DXOjsHTY7LnqnIX9PMvEV5/UNDP-Design-System?m=auto&node-id=450-8435&t=BCU5Vyp9c18KB0rj-1

And it looks like this:
<img width="435" alt="Screenshot 2024-10-07 at 5 07 44 PM" src="https://github.com/user-attachments/assets/23c83054-c8a8-4e53-a38d-f534659fa806">

**Comment by Jura** [comment]
There also should be a 32px spacer after the button

**Comment by theadamparker** [comment]
Looks great @CalebLuster
