### ISSUE TITLE
<a> tags must not have an explicit color

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1397]
It appears that the base minimal CSS file is setting `<a>` tags to use black as the color. This should not be the case, and those tags should inherit their color. 

<img width="1130" alt="Screen Shot 2024-10-09 at 1 42 43 PM" src="https://github.com/user-attachments/assets/3c9a8426-464d-4da0-b58a-ee3ff093bb12">

**Comment by Jura** [comment]
Just for the record, it is not a bug, but DS stylesheet is built this way, changing it requires complete regression testing for the package and also checking external projects already using DS (like www.undp.org)

**Comment by Jura** [comment]
Due to potential impact to the existing project we will keep it the way it is defined.
