### ISSUE TITLE
Threads icon should be added Storybook

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1401]
~~The Threads icon should be added to the footer. It should link here: https://www.threads.net/@undp~~
UPDATED: The Threads icon should be added to the icons list

**Comment by theadamparker** [comment]
The Threads icon (black and white versions) is available in [this branch of the design system Figma file](https://www.figma.com/design/WJSRV3CbcHuVWRQApwvWIm/branch/3zEfmhlAkzaphMPq8UH7CN/UNDP-Design-System?m=auto&node-id=505-12333&t=79V3kBsjA0j3AYYI-1).

<img width="1165" alt="Screen Shot 2024-10-16 at 10 37 46 AM" src="https://github.com/user-attachments/assets/90881062-96a4-4881-b3d7-8f0f714ff961">

**Comment by Jura** [comment]
@theadamparker , why do we need to add it to the Storybook? Specific social media channels are not part of our design, specific implementation should be handled outside of it, I believe. We definitely need to update https://github.com/undp/design-system-starter-template, but that's different story. 
Maybe we can Threads icon to the pool, but I don't think we should change the Footer component

**Comment by theadamparker** [comment]
Makes sense @Jura. Let's make the icon available as part of the design system, but it doesn't need to be added to the footer

**Comment by Jura** [comment]
Threads icon is a part of https://remixicon.com/ library. @CalebLuster , can you add a reference to remix icons to the respective documentation? Otherwise nothing else to do here.

**Comment by CalebLuster** [comment]
Added a commit for this in branch documentation-upadte-1401
