### ISSUE TITLE
Site title and menu items

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#1415]
The font weight of site title and menu items doesn't match Figma. [Currently in Storybook](https://design.undp.org/?path=/story/components-navigation-components-main-navigation-country-site-header--country-site-header-story) it's too light.

<img width="1252" alt="Screen Shot 2024-10-28 at 2 36 43 PM" src="https://github.com/user-attachments/assets/7d6918bd-e0ef-4d41-b850-ba71d01e9766">

**Comment by Jura** [comment]
@theadamparker , so, what do you think about this version: https://1415-site-title-and-menu-ite.design-system.pages.dev/?path=/story/templates-article-page--article-page-story?

**Comment by theadamparker** [comment]
@Jura this matches Figma, and looks better to me.

<img width="1361" alt="Screenshot 2024-11-22 at 2 27 04 PM" src="https://github.com/user-attachments/assets/63c24ad5-659d-4474-9d4d-655d1d4c1a87">
