### ISSUE TITLE
Long names overflow in the "author summary" component

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#510]
When long names are added to the "author summary" component they extend beyond their container and into the bio area. Long names also change the shape of the author image from a circle to a narrow ellipse. 

<img width="1156" alt="Screen Shot 2022-01-12 at 1 51 02 PM" src="https://user-images.githubusercontent.com/2205158/149213514-20f29a52-4960-4b8b-a227-9e03a303dcf5.png">

**Comment by Jura** [comment]
@theadamparker , which treatment is better? Test name: "Prapawedee Jarranaoterrratanakonmmmer"
1. Long words broken arbitrarily but words are kept together (no breaks on space): 
![image](https://user-images.githubusercontent.com/417604/180877458-c4282339-a653-4172-a0e6-4cc51f73da34.png)
2. Long words are broken, but browser is using maximum line length within the container breaking name on space as well: 
![image](https://user-images.githubusercontent.com/417604/180877599-5f816711-43ba-45f4-85e5-9dcd264fdf35.png)

**Comment by theadamparker** [comment]
@Jura 2 seems like a better approach. It shows as much unbroken text as possible.

**Comment by devjgigas** [comment]
Hi Jura,

I hope all is well.

Please remove my email address from your distro.

Thank you,

Jasmine

**Comment by Jura** [comment]
@devjgigas , this is the public repo and you have to withdraw your account from subscription list if you don't want to receive notifications. There is a small "unsubscribe" link at the bottom of every github notification email where you can manage that. You can also review your own list watching list and manage it here: https://github.com/watching
