### ISSUE TITLE
Long names overflow in the "author card" component

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#511]
When long names are added to the "author card" component they extend beyond their container. Long names also change the shape of the author image from a circle to a narrow ellipse. 

<img width="328" alt="Screen Shot 2022-01-12 at 2 25 18 PM" src="https://user-images.githubusercontent.com/2205158/149213960-39cef46d-20e8-4cdc-acb1-188d4c41056b.png">

This issue is similar to #510

**Comment by devjgigas** [comment]
Hi @theadamparker. I am having issues recreating this issue. [](url)


https://user-images.githubusercontent.com/61438849/161057057-3631c94e-251b-4a8f-a59e-7667919deb76.mp4

**Comment by theadamparker** [comment]
@devjgigas I'm seeing the same as you—this is the correct behavior. If everything seems to be in good working order we can close this issue.
