### ISSUE TITLE
UN Design System

### ISSUE THREAD

**Issue by Utzel-Butzel** [undp/design-system#7]
Dear UNDP-Team,

we have built the WFP UI-Kit which is a design system used by the World Food Programme (https://github.com/wfp/ui).
At the moment we are working with other UN organizations on a reusable core for a design system with `html/twig/react` implementation. It can be transformed to the needs and corporate identity of the specific organization.
Since we saw that you also plan on building a design system we are curious if you would be open for an exchange of ideas?

Best regards,

Robert

**Comment by Jura** [comment]
Hi @Utzel-Butzel ,
Sounds great! We would love to collaborate, let's get in touch directly, ping me at jura.khrapunov@undp.org and we will take it from there.
