### ISSUE TITLE
Default link doesn't display underline

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#887]
Currently the default link shows no visual distinction from plain text. It should have a red underline.

**Comment by theadamparker** [comment]
Related to #888

**Comment by Jura** [comment]
@theadamparker , @devjgigas , @Malakeldardiri , I think we should move default hyperlink treatment from Atoms section to generic typography. In my view default setting for <a> tag should be part of our baseline stylesheet and not optional plugin as it is done right now. What do you think? I'd also keep it animated by default, not just underlined. Please share you thoughts.

**Comment by theadamparker** [comment]
@Jura I agree that it should be moved to generic typography and animated by default.

**Comment by Jura** [comment]
closes #888
