### ISSUE TITLE
Sidebar doesn't display the 'chevron up'  to close the selected menu group

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#890]
<img width="429" alt="Screen Shot 2022-02-24 at 4 37 44 PM" src="https://user-images.githubusercontent.com/2205158/155612216-2e47d3ef-418f-4f24-b079-76d517733b73.png">

**Comment by paboden** [comment]
Hi @theadamparker 
Which component is this still an issue? Im looking at the Sidebar component and mine seems to work fine, though it doesn't have the MENU label on top.

![Screen Shot 2023-02-09 at 12 42 19 PM](https://user-images.githubusercontent.com/3878820/217934928-78501244-2b69-4c16-a53d-6c5ef0c305bc.png)

**Comment by theadamparker** [comment]
Hi @paboden, this applied only to the mobile breakpoint—that's when the "menu" label appears. However, we are not able to reproduce this issue exactly. It seems the the chevron is now present and functional, however the active menu item is not highlighted in blue as it should be on mobile. 

Can we reframe this issue to fix the missing blue background and white chevron for the menu at the mobile breakpoint?

**Comment by paboden** [comment]
@theadamparker got ya. PR submitted and ready to review soon.

**Comment by paboden** [comment]
merged and closed

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in Dev

**Comment by mrelevo** [comment]
verified in storybook and already implemented in Drupal
