### ISSUE TITLE
Design system font files should be made available for download

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#899]

**Comment by Jura** [comment]
@theadamparker , can you elaborate a bit? Do you mean as links on Storybook page? They are available for download or even hotlinking so let's narrow this down

**Comment by theadamparker** [comment]
@Jura in our [Website Requirements document](https://undp.sharepoint.com/sites/DigitalCommunications/SitePages/UNDP%27s-Website-requirements.aspx?xsdata=MDN8MDF8fDYxYzY4MzE4YWQzMzQwOTNiZTJjYmVjODlmNzk1MDhjfGIzZTVkYjVlMjk0NDQ4Mzc5OWY1NzQ4OGFjZTU0MzE5fDF8MHw2Mzc4MTc2MjA3MzY1OTMwMzB8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT0%3D&sdata=Y01WcXRLNHo3Q2JOOW1ZR1BEMTZ4bnU5MVpFeWRySGh2WVd6UlNZSDZjZz0%3D&ovuser=b3e5db5e-2944-4837-99f5-7488ace54319%2Cadam.parker%40undp.org&OR=Teams-HL&CT=1646165884303&sourceId=&params=%7B%22AppName%22%3A%22Teams-Desktop%22%2C%22AppVersion%22%3A%2228%2F22010300411%22%7D#useful-resources-%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B) there is a link to download UNDP's fonts. It would be ideal if this could be a zipped folder with all fonts, rather than requiring someone to navigate to the repo and download each individually.

**Comment by Jura** [comment]
@theadamparker , will this work: https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fundp%2Fdesign-system%2Ftree%2Fmaster%2Fdocs%2Ffonts ?

**Comment by Jura** [comment]
Done
