### ISSUE TITLE
Tabs container doesn't have internal padding

### ISSUE THREAD

**Issue by Jura** [undp/design-system#902]
Widget: https://design.undp.org/?path=/story/components-ui-components-tabs--tabs

Space on the screenshot below is top margin of the content, but component should have its own padding.

![image](https://user-images.githubusercontent.com/417604/156457977-d1bc4a55-bb19-4850-afd3-96a027aa3002.png)

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified

**Comment by mrelevo** [comment]
verified in Storybook. Not working in Drupal  https://global-dev.acquia.undp.org/blog/1157
