### ISSUE TITLE
Simple footer variant should use fewer legal links

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#903]
https://design.undp.org/?path=/story/components-ui-components-footer--footer&args=variant:simple

`Report Fraud, Abuse, Misconduct`, `Submit Social Or Environmental Complaint`, `Scam Alert` should be removed. Only `Terms Of Use` should be included.

**Comment by paboden** [comment]
@theadamparker @Jura Is it ok if I close issues that have their fix approved/merged? Do you have a preferred workflow for closing out an issue?

**Comment by Jura** [comment]
@paboden , we will take care of it.
The idea is to verify final implementation together with all current updates at https://develop.design-system.pages.dev/. As we need to wait until build and deployment is completed we are doing this final step in batches.

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in Dev

**Comment by mrelevo** [comment]
verified in storybook
