### ISSUE TITLE
Bio card title animation overflows its container. 

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#906]
https://design.undp.org/?path=/story/components-ui-components-cards-bio-card--bio-card

When the text within this card animates from left to right it visibly overflows the card container. Correct behavior is that the text shouldn't be visible outside of its container. 

<img width="389" alt="Screen Shot 2022-03-25 at 12 18 01 PM" src="https://user-images.githubusercontent.com/2205158/160160072-159c57b7-6f0b-4171-94c0-f99da35bbf5f.png">

**Comment by Jura** [comment]
@theadamparker  Fixed in Dev, please verify: https://develop.design-system.pages.dev/?path=/story/components-ui-components-cards-bio-card--bio-card

**Comment by theadamparker** [comment]
@Jura beautiful. Looks fixed.
