### ISSUE TITLE
Download modal styling needs updates

### ISSUE THREAD

**Issue by Jura** [undp/design-system#908]
https://design.undp.org/?path=/story/patterns-download-modal--download-modal
Some alignments are in order:
1. Dropdown should occupy entire width, right border should be aligned with the scrollbars
2. Links list should use entire available height of the widget, currently it is a bit shorter
![image](https://user-images.githubusercontent.com/417604/160243739-7a47b7dd-c02c-4cbb-998f-ab33ad9b380d.png)

**Comment by paboden** [comment]
merged and closed

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in Dev
