### ISSUE TITLE
Header (global and country) shouldn't change to tablet view for screens larger than 1024px

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#916]
Currently the headers lose the mega menu hover effect and switch to the collapsed menu with hamburger icon when the browser is <1440px. This should happen only for browser width <1024px. For everything >=1024px the full menu with mega menu hover effect should be used. 

UPDATE: flexible top level menu is separated to its own issue: #1098 based on the agreement with Chapter 3

**Comment by Malakeldardiri** [comment]
Here is the link to the final Figma mock up. Thanks 

https://www.figma.com/file/UimSg5ucd1QOgOz34JWpdv/Responsive-Navigation-Bar-Solutions?node-id=160%3A94875

**Comment by paboden** [comment]
Because the css work to fix 915 was so close to some of the fixes I had to do for this task, I just addressed it all in this issue.

**Comment by mrelevo** [comment]
verified in Dev

**Comment by mrelevo** [comment]
@paboden we just noticed that once you get into view in a browser <1440, the UNDP logo is no longer clickable. It becomes clickable again <1024.

This only occurs in the Global header

https://develop.design-system.pages.dev/iframe?args=&id=components-navigation-components-main-navigation-global-header--global-header&viewMode=story

![Image](https://user-images.githubusercontent.com/10246056/222802143-3b6bbde6-9df1-4b94-97e8-fce9b4738222.png)

**Comment by paboden** [comment]
@Jura @mrelevo - Created a new PR to address the logo - #1148

**Comment by Jura** [comment]
@paboden , there is another issue appeared, I'm afraid - now we are missing logo navigation (shrinking) when scrolling down the page: try https://916-fix-global-logo-link.design-system.pages.dev/?path=/story/templates-global-homepage--global-homepage for the viewport between 1024 and 1440 wide

**Comment by Jura** [comment]
@paboden , currently entire header is being shifted op on scroll there, this is not correct, only logo should contract/expand on scroll. Check the implementation for big screen (>1440) to use as an example and here is the screen recording from viewport in question with that undesired shift: 

https://user-images.githubusercontent.com/417604/223174665-f53d1c57-4e03-4b39-a86b-d91878e0ce2b.mp4

**Comment by paboden** [comment]
Hi @Jura, This is ready to review https://github.com/undp/design-system/pull/1148

**Comment by Jura** [comment]
@paboden , after last change the issue I reported is gone, but now Language switcher is shifted slightly up, the text is not aligned with the menu items anymore: 
![image](https://user-images.githubusercontent.com/417604/223726547-9a3e3628-feba-493e-8695-0300e77af3b0.png)

**Comment by theadamparker** [comment]
@paboden here's another approach at showing the misalignment issue. Note how the language switcher is sitting higher than the menu items.

<img width="1475" alt="Screenshot 2023-03-08 at 9 25 42 AM" src="https://user-images.githubusercontent.com/2205158/223738890-b63fc3d4-190b-40b8-a8dc-5968dbe8b493.png">

You can also see this change [in Chromatic](https://www.chromatic.com/test?appId=63d9556e407b5e99e6e9d920&id=6408561a92686ad2f4226848)

**Comment by theadamparker** [comment]
@paboden another small regression: For the Article template, the progress nav bar disappears between 1024px to 1440px. 

Screen capture of the issue:


https://user-images.githubusercontent.com/2205158/223826822-4a86409c-a953-48a3-8b35-6d7d44bd6a80.mov

**Comment by paboden** [comment]
@theadamparker This is ready to review again here - https://github.com/undp/design-system/pull/1148/ 
- I fixed the progress bar, which just needed the position from top adjusted between mobile and xlarge.
- I fixed the vertical position of the language switcher to match the position of the menu items in the global header (I also double checked the country header)

**Comment by Jura** [comment]
@mrelevo , over to you for verificaiton

**Comment by mrelevo** [comment]
Hi @paboden, all the issues have been resolved. However, a new one has been introduced. The language selector option now shows below the header

![image](https://user-images.githubusercontent.com/10246056/224154335-630f74cc-0f7c-4458-9e0b-3a3ceff0e7a9.png)

See correct behavior here

![image](https://user-images.githubusercontent.com/10246056/224154656-273c0e50-ad26-4f0d-ae04-4af8a722fc49.png)

And its fine as a standalone https://develop.design-system.pages.dev/?path=/story/components-ui-components-language-switcher--language-switcher

**Comment by Jura** [comment]
@mrelevo , over to you

**Comment by mrelevo** [comment]
looks good dev

**Comment by mrelevo** [comment]
verified in storybook and Drupal DEV
