### ISSUE TITLE
If image is followed by text - there should be a space in between

### ISSUE THREAD

**Issue by Jura** [undp/design-system#924]
Image element, immediately followed by text should have a bottom margin to prevent this: 
![image](https://user-images.githubusercontent.com/417604/164529875-9bb62cbc-afe2-4829-b097-162b8919844f.png)

**Comment by theadamparker** [comment]
@mrelevo see here:
- [Before fix](https://codepen.io/theadamparker/full/XWPRbXZ)
- [After fix](https://codepen.io/theadamparker/full/RwYVPrz)
Note the difference in space between photo and paragraph text below it.

**Comment by mrelevo** [comment]
verified

**Comment by mrelevo** [comment]
verified in Adam's code pen and also in Drupal
