### ISSUE TITLE
Links within a blockquote are formatted incorrectly

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#925]
Font size is too small when links are used in a blockquote. 

<img width="811" alt="Screen Shot 2022-04-22 at 10 23 52 AM" src="https://user-images.githubusercontent.com/2205158/164734030-6a0d9a36-a7b2-47b4-9940-70c12ae36cba.png">

Live example: 
https://codepen.io/theadamparker/pen/gOoymae

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by theadamparker** [comment]
Verified in dev

https://codepen.io/theadamparker/pen/NWLjGBO

**Comment by mrelevo** [comment]
verified using Adam's codepen, also already implemented in Drupal
