### ISSUE TITLE
Bio card image is misaligned and does not scale

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#927]
The [bio card component](https://design.undp.org/?path=/story/components-ui-components-cards-bio-card--bio-card) uses a portrait image above text in a gray container. The width of the image should match the width of the container beneath it. 

Currently the image and container are misaligned.
<img width="751" alt="Screen Shot 2022-05-10 at 2 29 13 PM" src="https://user-images.githubusercontent.com/2205158/167697821-fcab3346-30bd-40a1-aba1-3bb39843880f.png">

**Comment by Jura** [comment]
Bio card image should also retain 3:4 aspect ratio regardless the image src used

**Comment by Jura** [comment]
Apparently not an issue anymore, closing
