### ISSUE TITLE
Accent color should be implemented as a global variable

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#930]
Currently the accent color (yellow, green, red, or azure) used in hover effects, stats cards, etc. is set at the component level. This allows a page to use a mix of colors when there should only be one accent color applied consistently throughout a website.

Creating a global variable would allow site creators to define the accent color in a single place and have that color be inherited by all components using an accent color. This would eliminate the mix-and-match effect that can currently being created.

**Comment by theadamparker** [comment]
Hi @paboden, the following components are currently using the accent color:

## Components

[Author image](https://design.undp.org/?path=/story/foundation-images-author-image--author-image) (hover color)
[Author](https://design.undp.org/?path=/story/components-ui-components-authors-author--author) (hover color)
[Author card](https://design.undp.org/?path=/story/components-ui-components-authors-author-card--author-card) (hover color)
[Bio card](https://design.undp.org/?path=/story/components-ui-components-cards-bio-card--bio-card) (hover color)
[Content card with image](https://design.undp.org/?path=/story/components-ui-components-cards-content-card-with-image--with-image) (hover color)
[Content card without image with emphasize](https://design.undp.org/?path=/story/components-ui-components-cards-content-card-without-image-with-emphasize--with-emphasize)
[Publication module](https://design.undp.org/?path=/story/components-ui-components-cards-download-card--publication-module) (hover color)
[Card module](https://design.undp.org/?path=/story/components-ui-components-cards-download-card--card-module) (hover color)
[Featured card](https://design.undp.org/?path=/story/components-ui-components-cards-featured-card--featured-card) (hover color)
[Image reveal card](https://design.undp.org/?path=/story/components-ui-components-cards-image-reveal-card--image-reveal-card) (hover color)
[Publication card](https://design.undp.org/?path=/story/components-ui-components-cards-publication-card--publication-card) (hover color)
[Stats card](https://design.undp.org/?path=/story/components-ui-components-cards-stats-card--stats-card) (hover color)
[Pagewide featured content card](https://design.undp.org/?path=/story/components-ui-components-pagewide-featured-content-card--pagewide-featured-content-card) (hover color)
[Stats](https://design.undp.org/?path=/story/components-ui-components-stats--stats) (hover color)
[Stats card slider](https://design.undp.org/?path=/story/components-ui-components-stats-card-slider--stats-card-slider) (imports individual stats cards)
[Callout](https://design.undp.org/?path=/story/components-ui-components-text-callout--callout) (when the color background is used it should reference the global variable)

## Patterns

[Content cards](https://design.undp.org/?path=/story/patterns-card-grids-content-cards--content-cards) (imports content card with image)
[Content cards with and without images](https://design.undp.org/?path=/story/patterns-card-grids-content-cards-with-and-without-image--content-cards-with-and-without-image) (imports multiple cards)
[Featured cards](https://design.undp.org/?path=/story/patterns-card-grids-featured-cards--featured-cards) (imports featured card)
[Image reveal cards](https://design.undp.org/?path=/story/patterns-card-grids-image-reveal-cards--image-reveal-cards) (imports image reveal card)
[Stats slider (two rows)](https://design.undp.org/?path=/story/patterns-stats-slider-two-rows--stats-slider-two-rows) (imports stats card)
[Progress bar navigation](https://design.undp.org/?path=/story/utilities-progress-bar-navigation--progress-bar-navigation)

## Templates

Most templates import some of the above components. 

---

Note that most card components are currently using Storybook controls to display one of four color options.

**Comment by Jura** [comment]
@paboden, there are four primary accent colors, you can see them here: https://design.undp.org/?path=/docs/foundation-colors--page. There are also darker/lighter variations, but the are used for hover effects and alike, sort of utilities for the primary four.
What we are looking for here is an enhancement for the entire components set where we can define accent color at any level and all respective component which are located inside that container will follow that setting.
Example:
```
<section class="accent-green">
  <div id="card1" div class="content-card">
  <!-- content card markup --> 
  </div>
  <div id="card2" div class="content-card accent-red">
  <!-- content card markup --> 
  </div>
</section>
<div id="card3" div class="content-card">
<!-- content card markup --> 
</div>
```
In this example **card1** will use green accent color even though it is not set at the card level - its container has .accent-green assigned. **card2** will use red accent color since that class is set on the component itself. And **card3** will use default yellow accent color since there are no global or local modifiers applicable to that widget.
In real world scenarios accent can be set on the <main> element or even on body and all elements should recognize that global modifier and although observe more specific modifiers if set.

**Comment by Jura** [comment]
@paboden , we are almost there, one last tiny issue we've just discovered, [Content card without image](https://930-accent-color-should-be-i.design-system.pages.dev/?path=/story/components-ui-components-cards-content-card-without-image-without-emphasize--without-emphasize) shouldn't have accent color applied at all. Regardless of the global modifier it uses light grey background on hover all the time. Everything else looks good to me, once this is fixed I'll approve PR

**Comment by paboden** [comment]
Hi @Jura, I've removed the accent color to the content card without image. Go ahead and retest.

**Comment by Jura** [comment]
@mrelevo , for verification, changes are being built into https://develop.design-system.pages.dev/ right now
