### ISSUE TITLE
Reorder subitems in Getting started section

### ISSUE THREAD

**Issue by Jura** [undp/design-system#931]
After implementing automatic alphabetical sorting of Storybook menu items Getting started is showing Browser support section by default while it has to be Intro

**Comment by Jura** [comment]
@theadamparker , what do you think about this (using letter prefix for section titles to enforce specific order)?

![Image](https://user-images.githubusercontent.com/417604/168452637-24c4605d-7132-4a09-91a6-2a7cd576162d.png)

**Comment by theadamparker** [comment]
@jur

**Comment by Jura** [comment]
There are some other ways how to handle it - we can assign Intro to a separate category (Intro/Intro) and make it appearing before Getting started, no A. tricks required. We can also drop automatic sorting but in that case we will need to maintain specific order manually - it is quite cumbersome at that scale.
