### ISSUE TITLE
Stats cards cannot properly display content of varying lengths

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#932]
Current implementation
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/2205158/168826564-c9547922-6313-43ba-9d23-43fbf0138d8c.png)

**Comment by Jura** [comment]
- Stats should use entire available width up to the max font size
- Sections should be aligned vertically
- Text underneath the main stat shouldn't be adjusted automatically

**Comment by Jura** [comment]
@theadamparker, check out the PR so I can merge it to dev and prepare for release: https://github.com/undp/design-system/pull/940
