### ISSUE TITLE
Site title line height is incorrect 

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#933]
Currently the line height is "1rem." Line height should not use a unit, and the correct line height is `1.142` (sorry it's not a nice round number @Jura but this matches the specs in Figma).

Current implementation looks like this:
<img width="341" alt="Screen Shot 2022-05-20 at 2 38 16 PM" src="https://user-images.githubusercontent.com/2205158/169592120-73ea965d-9b20-48be-874c-c5f02edc74e9.png">

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by theadamparker** [comment]
Verified in dev

**Comment by mrelevo** [comment]
verified in storybook and Drupal
