### ISSUE TITLE
Lightbox gallery error "cannot read properties of undefined (reading 'MEDIUM')"

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#939]
https://design.undp.org/?path=/story/components-ui-components-gallery-lightbox-gallery--lightbox-gallery
<img width="1161" alt="Screen Shot 2022-06-02 at 4 26 01 PM" src="https://user-images.githubusercontent.com/2205158/171731905-b10ef133-4410-4b91-b396-5c46cf3bc182.png">

**Comment by paboden** [comment]
Hi @theadamparker, is this error still occurring for you? I'm not sure how to reproduce. The component seems to load fine locally.

**Comment by mrelevo** [comment]
verified in storybook
