### ISSUE TITLE
Add donate button to country site header

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#941]
The donate button should be an optional part of the country header.

**Comment by paboden** [comment]
@theadamparker is there a design for the button in the global header? Does it need to be added to the global header or only the country header?

**Comment by theadamparker** [comment]
@paboden it should only be added to the country header

**Comment by theadamparker** [comment]
@Jura the CTA is disabled by default, so I don't think it needs to be part of that template's header.

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified

**Comment by mrelevo** [comment]
verified in Storybook
