### ISSUE TITLE
Logo and menu items are misaligned in headers

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#949]
https://design.undp.org/?path=/story/components-navigation-components-main-navigation-country-header--country-header
https://design.undp.org/?path=/story/components-navigation-components-main-navigation-global-header--global-header

<img width="1507" alt="Screen Shot 2022-06-09 at 12 23 11 PM" src="https://user-images.githubusercontent.com/2205158/172896655-ea35b3c0-d38c-416b-8c76-1e6e597e6b3e.png">

<img width="1504" alt="Screen Shot 2022-06-09 at 12 23 02 PM" src="https://user-images.githubusercontent.com/2205158/172896670-ce4a29a8-fb56-4d8b-9df5-75db15122537.png">

**Comment by Jura** [comment]
It seems stylesheet hasn't loaded fully in your case, that's what I see:
![image](https://user-images.githubusercontent.com/417604/172899485-46e26b63-3122-41f9-ae55-96e051dad1f0.png)

**Comment by mrelevo** [comment]
I see the same as Adam

![image](https://user-images.githubusercontent.com/10246056/172903856-03e18178-22a0-417b-acbc-8f8e4cb0a37b.png)

**Comment by Jura** [comment]
Yeah, we just did it interactively and I see it. The issue is not universal so i need to find out why it is happening

**Comment by Jura** [comment]
Note to myself, it seems the issue appeared between following builds:
last known good build: https://8cd85435.design-system.pages.dev/?path=/story/components-navigation-components-main-navigation-global-header--global-header
next build displaying broken widgets: https://c193c0bb.design-system.pages.dev/?path=/story/components-navigation-components-main-navigation-global-header--global-header
First bad version is based on this commit: https://github.com/undp/design-system/commit/a922da6678662aebe82194ee937ae88010c3bb89

**Comment by Jura** [comment]
@theadamparker , verify and sign off for release: https://develop.design-system.pages.dev/?path=/story/components-navigation-components-main-navigation-country-header--country-header

**Comment by theadamparker** [comment]
@Jura this fix is verified.
