### ISSUE TITLE
Frosted background needs a different treatment for Firefox

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#958]
Firefox doesn't display the `backdrop-filter` CSS property. To ensure proper contrast browsers not supporting this property should have less opacity than those that support the blur.

Screenshot of Chrome vs. Firefox
![Screen Shot 2022-06-16 at 1 31 28 PM](https://user-images.githubusercontent.com/2205158/174131544-a423361b-e51d-4ce7-8c17-050e7c5d27d3.png)

**Comment by paboden** [comment]
Hi @theadamparker , I've adjusted the css to reduce the opacity of the img if the blur effect is not supported.

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by theadamparker** [comment]
Verified in dev. Firefox supports backdrop-filter in versions >102, but this was verified in version 102 via Browserstack.

**Comment by mrelevo** [comment]
verified in storybook and Global DEV
