### ISSUE TITLE
Footer links should accept a flexible number of items

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#984]
5 items breaks the layout.
![Screen Shot 2022-06-29 at 10 30 49 PM](https://user-images.githubusercontent.com/2205158/176580086-cdea682e-7daa-467c-92dc-e538d535ebfc.png)

**Comment by paboden** [comment]
@theadamparker @Jura -- https://github.com/undp/design-system/pull/1114

I've attached some screen shots of how my setup can adjust from medium to x-large, in this case with 6 menu sections

It can handle up to 3 across on medium, 4 across on large, and 6 across on x-large. It moves additional menu sections to a new row, while always keep the search, globe, term links and social media links section off to the right side (in-line if there is room)

let me know what you think

x-large
![Screen Shot 2023-01-31 at 11 56 00 PM](https://user-images.githubusercontent.com/3878820/215988436-7857fa64-983d-42fa-b826-870df2ec0571.png)

medium
![Screen Shot 2023-01-31 at 11 55 37 PM](https://user-images.githubusercontent.com/3878820/215987436-4a4def16-a862-404b-8919-c2c42bf294b4.png)

large
![Screen Shot 2023-01-31 at 11 55 46 PM](https://user-images.githubusercontent.com/3878820/215987440-e392ee2e-7f3f-4fcc-8929-77a52de75605.png)

Example of 8 items
![Screen Shot 2023-01-31 at 11 24 07 PM](https://user-images.githubusercontent.com/3878820/215988519-90b6241f-f857-40df-a6c7-d12b83e2d0f5.png)

Example of only 3 items
![Screen Shot 2023-01-31 at 11 56 25 PM](https://user-images.githubusercontent.com/3878820/215988478-1ef0e9fd-2815-451e-8dea-c7c37aecab4a.png)

**Comment by theadamparker** [comment]
@paboden the wrapping approach is exactly what we need. However, the legal links (report fraud, terms of use, etc.) should remain aligned with the top row. 

Example:
![Screen Shot 2023-02-01 at 3 21 51 PM](https://user-images.githubusercontent.com/2205158/216155979-e66e282c-c9ec-4b56-9fe6-0ba5b68494cd.png)

This will mean fewer items can be placed in the first row, but it is more closely aligned with the original visual appearance.

**Comment by paboden** [comment]
@theadamparker pushed up a fix. Take a look and let me know what you think. Cheers

**Comment by Jura** [comment]
Verified https://develop.design-system.pages.dev/?path=/story/templates-country-homepage--country-homepage

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in Dev

**Comment by mrelevo** [comment]
verified in storybook
