### ISSUE TITLE
Button should include an option to use the download icon

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#985]
![Screen Shot 2022-06-30 at 7 47 20 PM](https://user-images.githubusercontent.com/2205158/176796475-0adc8aa6-1f1e-4533-8efd-24451c2af7f0.png)

**Comment by paboden** [comment]
merged and closed

**Comment by Jura** [comment]
@paboden change label for the new option from "For_Primary" to "Icon"
![image](https://user-images.githubusercontent.com/417604/221682390-5d1e5bab-37a4-4d1f-a495-b85d378a441c.png)

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in DEV

**Comment by mrelevo** [comment]
verified in storybook
