### ISSUE TITLE
Storybook homepage should be redesigned

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#986]
The homepage should be redesigned to include links to Figma, Github, and include the sizzle reel.

**Comment by theadamparker** [comment]
New homepage design is [available here](https://www.figma.com/proto/TjY8gbxvqDmKQzkDSaSfwx/Storybook-Assets?page-id=4%3A546&node-id=4%3A639).

<img width="504" alt="Screen Shot 2022-07-22 at 9 59 52 AM" src="https://user-images.githubusercontent.com/2205158/180455234-86e9970b-5293-46f7-8afb-8017760d1348.png">

**Comment by paboden** [comment]
Hi @Jura and @theadamparker,
I've added a test version of the Intro documentation (IntroTest.stories.mdx), to see if that setup is where you guys are looking to head with the documentation. Let me know what you think. We can get a PR going if we want to get a dev environment in place for easier reviewing.
Are all story document files going to be designed or just the ones in the "Getting Started" section

**Comment by theadamparker** [comment]
@paboden yes this is exactly what we're after. This is the only story document file we plan to design. The rest can remain as they are.

**Comment by paboden** [comment]
@theadamparker Do you have a better header video/gif? I just took a screen recording from the figma preview and wedged it into place.

**Comment by Jura** [comment]
MP4: https://undp.widen.net/content/piy26v2s1n/mp4/undp-design-system-roll.mp4?quality=hd&u=cvx5ij

embeddable player (just in case): 
`<div style="position:relative;width:100%;height:0;padding-bottom:56.25%;"><iframe src="https://undp.widen.net/view/video/piy26v2s1n/undp-design-system-roll.mp4?u=cvx5ij" webkitallowfullscreen mozallowfullscreen allowfullscreen title="Video for &quot;undp-design-system-roll.mp4&quot;" frameborder="0" allowtransparency="true" scrolling="no" style="position:absolute;top:0;left:0;width:100%;height:100%;" ></iframe></div>`

**Comment by theadamparker** [comment]
@paboden see above

**Comment by paboden** [comment]
@theadamparker @Jura, I wasn't able to get the iframe embed working (autoplay wouldn't take effect and couldn't get controls hidden), but I was able to extract the video files and get it working thru a 'video' tag (with autoplay and hidden controls). 

Take a look and let me know if you like.

**Comment by Jura** [comment]
@paboden , video is not autoplaying: https://986-storybook-homepage-shoul.design-system.pages.dev/?path=/story/getting-started-intro--page, at least not in Chrome/Win11
And I'd also ask you to use a single mp4 source from our DAM/CDN verbatim: https://undp.widen.net/content/piy26v2s1n/mp4/undp-design-system-roll.mp4?quality=hd&u=cvx5ij, you can remove other renditions from this github repo

**Comment by Jura** [comment]
And to clarify, video doesn't autoplay on the first load only, in browser without cached assets. When I browse that Storybook instance and return to the intro page after a few clicks - video plays just fine

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in Dev

**Comment by mrelevo** [comment]
verified in storybook
