### ISSUE TITLE
Page hero component should use an optional CTA

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#997]

**Comment by Jura** [comment]
Do you think we should implement it in the Storybook? Those are elements which are sufficiently represented throughout the site, specific implementation when we are including CTA to the Hero is our Site Studio matter, same way as we can enrich it with modal window if necessary. Or incorporate buttons. i don't think it is **required** to be in Storybook.

**Comment by theadamparker** [comment]
@Jura it's a treatment we can officially endorse by including it in Figma and Storybook. A small enhancement to the component that takes the guesswork out of creating it, and ensures a consistent treatment with the homepage hero.

**Comment by Jura** [comment]
Ok, no problem

**Comment by theadamparker** [comment]
CTA has been added to the "Page hero" component in Figma.
<img width="950" alt="Screen Shot 2022-07-20 at 3 28 45 PM" src="https://user-images.githubusercontent.com/2205158/180065955-a132893f-8777-4bfe-bfaa-ca07855e5c80.png">

**Comment by Jura** [comment]
@paboden , CTA control should use properly formatted label, "CTA", instead of current "cta_enabled". it also should use On/Off notation for switcher instead of False/True
![image](https://user-images.githubusercontent.com/417604/219696635-1cde125b-b949-470a-b64a-d94f2721e09c.png)

**Comment by paboden** [comment]
The PR for this issue is ready to review again. The storybook controls have been cleaned up.
#1130

**Comment by Jura** [comment]
Verified

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in Dev

**Comment by mrelevo** [comment]
verified in storybook, already in Drupal
